### PR TITLE
Unique Id of UserInfo should be field "oid" and not "object_id"

### PR DESCRIPTION
**Pull request by myosotys**
I only change the constant ID_TOKEN_OBJECT_ID from "object_id" to "oid"
And UserInfo get this field in the customClaim of the object Claim
<a href='#crh-start'></a><a href='#crh-data-%7B%22processed%22%3A%20%5B%22https%3A//github.com/AzureAD/azure-activedirectory-library-for-java/pull/36%23issuecomment-115152962%22%2C%20%22https%3A//github.com/AzureAD/azure-activedirectory-library-for-java/pull/36%23issuecomment-115157809%22%2C%20%22https%3A//github.com/AzureAD/azure-activedirectory-library-for-java/pull/36%23issuecomment-115158321%22%2C%20%22https%3A//github.com/AzureAD/azure-activedirectory-library-for-java/pull/36%23issuecomment-118167258%22%5D%2C%20%22comments%22%3A%20%7B%22General%20Comment%22%3A%20%7B%22html_url%22%3A%20%22https%3A//github.com/AzureAD/azure-activedirectory-library-for-java/pull/36%23issuecomment-115152962%22%2C%20%22comments%22%3A%20%5B%7B%22body%22%3A%20%22Hi%20__%40myosotys__%2C%20I%27m%20your%20friendly%20neighborhood%20Microsoft%20Open%20Technologies%2C%20Inc.%20Pull%20Request%20Bot%20%28You%20can%20call%20me%20MSOTBOT%29.%20Thanks%20for%20your%20contribution%21%5Cr%5Cn%20%20%20%20%3Cspan%3E%5Cr%5Cn%20%20%20%20%20%20%20%20In%20order%20for%20us%20to%20evaluate%20and%20accept%20your%20PR%2C%20we%20ask%20that%20you%20sign%20a%20contribution%20license%20agreement.%20It%27s%20all%20electronic%20and%20will%20take%20just%20minutes.%20I%20promise%20there%27s%20no%20faxing.%20https%3A//cla2.msopentech.com.%5Cr%5Cn%20%20%20%20%3C/span%3E%5Cr%5Cn%5Cr%5CnTTYL%2C%20MSOTBOT%3B%5Cr%5Cn%22%2C%20%22created_at%22%3A%20%222015-06-25T07%3A52%3A58Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/9519461%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/msotclas%22%7D%7D%2C%20%7B%22body%22%3A%20%22fixes%20%2336%20%22%2C%20%22created_at%22%3A%20%222015-06-25T08%3A12%3A27Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/5969632%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/myosotys%22%7D%7D%2C%20%7B%22body%22%3A%20%22__%40myosotys__%2C%20Thanks%20for%20signing%20the%20contribution%20license%20agreement%20so%20quickly%21%20Actual%20humans%20will%20now%20validate%20the%20agreement%20and%20then%20evaluate%20the%20PR.%5Cr%5Cn%3Cbr%20/%3EThanks%2C%20MSOTBOT%3B%22%2C%20%22created_at%22%3A%20%222015-06-25T08%3A14%3A21Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/9519461%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/msotclas%22%7D%7D%2C%20%7B%22body%22%3A%20%22Can%20you%20submit%20this%20to%20dev%20branch%3F%20We%20merge%20changes%20to%20master%20after%20updating%20version%20and%20changelog.%22%2C%20%22created_at%22%3A%20%222015-07-02T21%3A02%3A15Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/466805%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/omercs%22%7D%7D%5D%2C%20%22title%22%3A%20%22General%20Comment%22%7D%7D%7D'></a>
<a href='https://www.codereviewhub.com/'></a>
- [ ] <a href='#crh-comment-General Comment'></a> &nbsp;<b><a href='https://github.com/AzureAD/azure-activedirectory-library-for-java/pull/36#issuecomment-115152962'>General Comment</a></b>
- <a href='https://github.com/msotclas'></a> Hi __@myosotys__, I'm your friendly neighborhood Microsoft Open Technologies, Inc. Pull Request Bot (You can call me MSOTBOT). Thanks for your contribution!
<span>
In order for us to evaluate and accept your PR, we ask that you sign a contribution license agreement. It's all electronic and will take just minutes. I promise there's no faxing. https://cla2.msopentech.com.
</span>
TTYL, MSOTBOT;
- <a href='https://github.com/myosotys'></a> fixes #36
- <a href='https://github.com/msotclas'></a> __@myosotys__, Thanks for signing the contribution license agreement so quickly! Actual humans will now validate the agreement and then evaluate the PR.
<br />Thanks, MSOTBOT;
- <a href='https://github.com/omercs'></a> Can you submit this to dev branch? We merge changes to master after updating version and changelog.

<a href='https://www.codereviewhub.com/AzureAD/azure-activedirectory-library-for-java/pull/36?mark_as_completed=1'></a>&nbsp;<a href='https://www.codereviewhub.com/AzureAD/azure-activedirectory-library-for-java/pull/36?approve=1'></a>&nbsp;<a href='https://github.com/AzureAD/azure-activedirectory-library-for-java/pull/36'></a>
<a href='#crh-end'></a>

### CODE REVIEW

**Comment by brandwe** [comment]
This pull request is now managed with CodeReviewHub. <a href='https://github.com/AzureAD/azure-activedirectory-library-for-java/pull/36'>Refresh</a>.<a href='#crh-update-none'></a>

**Comment by msotclas** [comment]
Hi __@myosotys__, I'm your friendly neighborhood Microsoft Open Technologies, Inc. Pull Request Bot (You can call me MSOTBOT). Thanks for your contribution!
    <span>
        In order for us to evaluate and accept your PR, we ask that you sign a contribution license agreement. It's all electronic and will take just minutes. I promise there's no faxing. https://cla2.msopentech.com.
    </span>

TTYL, MSOTBOT;

**Comment by myosotys** [comment]
fixes #36

**Comment by msotclas** [comment]
__@myosotys__, Thanks for signing the contribution license agreement so quickly! Actual humans will now validate the agreement and then evaluate the PR.
<br />Thanks, MSOTBOT;

**Comment by omercs** [comment]
Can you submit this to dev branch? We merge changes to master after updating version and changelog.

**Pull request closed without merging**
