### PR TITLE
Remove unsafe casting to java.security.RSAPrivateKey when not necessary

### PR DESCRIPTION
**Pull request by epot**
Proposal to fix "Fails to create a AsymmetricKeyCredential from a windows store certificate" #110. Please note that I remove a check that may be important.

### CODE REVIEW

**Comment by epot** [comment]
I followed the cla signing procedure, even if it looks still needed here. I hope this is just a latency in the signing process.

**Comment by msftgits** [comment]
Hi, I am closing and re-opening this PR to bump the CLA bot. Sorry for the inconvenience!

**Comment by epot** [comment]
Any update ?

**Comment by epot** [comment]
Ping ?

**Comment by SomkaPe** [comment]
Hi @epot , PR #118 with corresponding changes was submitted, will merge to the dev after review

**Pull request closed without merging**
