### PR TITLE
Implement the device code flow

### PR DESCRIPTION
**Pull request by cosmincojocar**
This is the implementation of the device code flow. In addition some slight refactoring was done to integrate the device code flow within the existing implementation.

cc @SomkaPe @kpanwar @slyons psignoret

### CODE REVIEW

**Comment by cosmincojocar** [comment]
@navyasric any chance to merge soon this PR?

**Comment by cosmincojocar** [comment]
I'm closing this since is older than 6 months. It doesn't seem to be an interest in merge it.

**Comment by navyasric** [comment]
@cosmincojocar Sorry for the long delay in getting to this PR. Our team is taking a look at it and will keep you posted.

**Comment by sangonzal** [comment]
@cosmincojocar your implementation of the device code flow was refactored and merged in #206 and released in version 1.5.0. Thank you for contributing!

**Pull request closed without merging**
