### PR TITLE
acquireToken by providing clientId, clientSecret, username, password

### PR DESCRIPTION
**Pull request by zzeekk**
I tried to use the PowerBI API with non-interactive authentication and the following acquireToken call:
_token = authContext.acquireToken(resourceUri, clientId, username, pw, null).get()_
This results in the following error:
_com.microsoft.aad.adal4j.AuthenticationException: {"error_description":"AADSTS90014: The request body must contain the following parameter: 'client_secret or client_assertion'.\r\nTrace ID: dd5f457c-9bd0-4f3f-a999-74f9c539f544\r\nCorrelation ID: 961ed1cc-fea3-4217-88bb-f361b9b2e267\r\nTimestamp: 2016-08-14 06:57:16Z","error":"invalid_request"}_

Currently an acquireToken method with parameters clientId, clientSecret, username, password is missing. This pull-request fixes this and makes it possible to get a Token which can be used with PowerBI API.

### CODE REVIEW

**Comment by mparker** [comment]
Will someone with write access please pull this? This fix is required for any AAD web application that needs app+user auth, not just PowerBI.

**Comment by M3lkior** [comment]
+1

**Comment by psignoret** [comment]
In general, the practice of collecting a user's username and password should be (and can be, in almost every case) avoided. Not only is it a security risk, but it will severely limit the capabilities that your app can offer. See https://github.com/AzureAD/azure-activedirectory-library-for-dotnet/issues/482 for more discussion on the topic.

The [Resource Owner Password Credentials Grant](https://tools.ietf.org/html/rfc6749#section-4.3) flow for confidential clients (which is what you are trying to invoke with a client ID, client secret, username and password) is not a supported flow with Azure AD. (It will soon stop working on the service side, even if you try manually craft the request.) This flow is only supported for apps registered as native clients (i.e. public clients, in OAuth 2.0 terminology), which don't have client credentials. (Again: you _don't_ want to do that in a web app.)

If you are building a web app (e.g. @mparker, @M3lkior), then you would want to use the Authorization Code Grant flow, which starts by [redirecting](https://github.com/AzureAD/azure-activedirectory-library-for-java/blob/aadff817c3fa01462051941c198201fe621b6f00/src/samples/web-app-samples-for-adal4j/src/main/java/com/microsoft/aad/adal4jsample/BasicFilter.java#L110) the user to the authorization endpoint (e.g. as constructed in the web app sample by [`getRedirectUrl()`](https://github.com/AzureAD/azure-activedirectory-library-for-java/blob/dev/src/samples/web-app-samples-for-adal4j/src/main/java/com/microsoft/aad/adal4jsample/BasicFilter.java#L237)), and then using `acquireTokenByAuthorizationCode` to exchange the returned authorization code for the ID Token, Access Token and Refresh Token. The resulting Access Token will will be in the app+user context, and can be used against Power BI.

**Comment by M3lkior** [comment]
In my case, i'm using Adal4j with Spring Security to provide an authentification endpoint for my users.
SO I can not  use the Authorization Code Grant flow i think.

My workflow : 
- A front end app use my backend REST endpoint to authenticate an user
- this rest endpoint, based on spring security, try to authenticate the user thanks to Adal4j, by passing his username & password
- if Adal4j authentication is done, i call the Azure Graph API to get more details about my user
- and finally, my backend generate a JWT token based on authentication result, provide to the client APP

**Comment by zzeekk** [comment]
Finally some traffic on this thread :-)

@psignoret: my use case is a service on azure, which collects sensor data and pushes it to PowerBI real-time. There is no user on the way... but PowerBI needs clientAssertion & user. How can i authenticate against PowerBI-API as a service?

**Comment by psignoret** [comment]
@M3lkior, can you tell me more about your front-end app? What platforms is it running on? (Native client on desktop, on mobile, in browser (i.e. JavaScrip SPA), etc.)

**Comment by M3lkior** [comment]
My front-end app is running on node.js (express & vue.js), but Azure AD is consumed by my backend which is based on Spring / running under  tomcat8

**Comment by psignoret** [comment]
@zzeekk: Ah, this is similar to the scenario with the Dynamics CRM Online API, described in [AzureAD/azure-activedirectory-library-for-dotnet#482](https://github.com/AzureAD/azure-activedirectory-library-for-dotnet/issues/482#issuecomment-262815609). In the comment that link will take you to, I describe the different options, and conclude that the only way to use that API from a service which does not ever have user interaction is, in fact, to use a user account as a service account.

The issue stems from the fact that the Power BI REST API does not expose any app-only permissions, and does not understand the concept of a an application authenticating _as itself_ (as opposed to in the context of a signed-in user).

The only two ways I know of to work around this limitation are a) to generate and access token and refresh token via interactive authentication, and then use the refresh token to get fresh access and refresh tokens, and b) to use a user account as a service account. The main issue with the former approach is that the app needs to run more or less continuously to ensure the refresh token doesn't expire. To do the latter:

1. Register a *native client* application with the necessary permissions to Power BI:

    Registering a native client application in the Azure portal

    Selecting delegated permissions to Power BI Service in the Azure portal

2. Use the "Grant Permissions" button to consent to the app on behalf of users:

    Granting permissions in the Azure portal

3. Create a new cloud-only user (e.g. power-bi-service-account@contoso.onmicrosoft.com). Generate and set a strong random password for this user. Set the password to never expire (or leave it with an expiry, but set a reminder somewhere). This user's password is a *[secret](https://www.youtube.com/watch?v=_YhpauKGgQ4)*, equivalent to the client secret when you register an app. [Keep it secret](https://docs.microsoft.com/en-us/azure/service-fabric/service-fabric-application-secret-management), [keep it safe](https://azure.microsoft.com/en-us/services/key-vault/). (E.g. don't check it in to GitHub, avoid putting it in code at all, etc.)

4. In your service code, use the ADAL method for public clients to obtain the access token to Power BI:

        public Future<AuthenticationResult> acquireToken(
            final String resource,
            final String clientId,
            final String username,
            final String password,
            final AuthenticationCallback callback)

**Comment by fatmanmclone90** [comment]
Does anyone know if this is going to be merged still?

**Comment by psignoret** [comment]
@fatmanmclone90 It is highly unlikely that this pull request will be merged, incide it invokes a flow that is not supported by Azure AD. (See the conversation above for more detail.) I'll make sure someone from that team passes by to give a definitive answer and closes the PR.

**Comment by kpanwar** [comment]
@psignoret is correct. This flow will actually be disabled on the service side in the near future.

**Comment by westleyMS** [comment]
@kpanwar is there a resource that lists the supported variations of the flows etc? In the main OAuth flow docs it seems they don't call out which clients it works for (public / confidential).

**Pull request closed without merging**
