### PR TITLE
Update commons-codec dependency

### PR DESCRIPTION
**Pull request by conniey**
Updates the commons-codec dependency.

### CODE REVIEW

**Comment by sangonzal** [comment]
Hi @conniey, can you provide a reason you'd like to make this change? We don't have plans for releasing any more versions for ADAL. Instead it's recommended that people use MSAL.

**Comment by conniey** [comment]
@sangonzal It's used as a test dependency in some client libraries in azure/azure-sdk-for-java. There are CVEs in the version of commons-codec used here which consequently shows up in our reports.

**Comment by sangonzal** [comment]
Ok. In that case we should merge this in and do a release. FYI @SomkaPe @navyasric @henrik-me

**Comment by conniey** [comment]
@sangonzal Is there any time period when this can be merged and another package released? :) Thanks!

**Comment by SomkaPe** [comment]
@conniey 1.6.5 version is released

**Comment by conniey** [comment]
@SomkaPe Thanks!

**Pull request merged**
