### PR TITLE
Added support for interactive authentication.

### PR DESCRIPTION
**Pull request by avranju**
This PR adds support for interactive authentication flows for the adal4j
library. The browser UI component is implemented using Eclipse SWT's cross
platform browser component. The browser UI is implemented in the
adal-ad-interactive-auth module. All the new code for implementing interactive
auth in the adal4j module is in the com.microsoft.aad.adal4j.interactive.*
package.

The maven project is now a multi-module maven project containing the
browser UI module and the adal4j module. The browser UI module -
adal-ad-interactive-auth - is built and the binaries are hosted in the
github repo for all supported platforms and architectures (Linux, OSX and
Windows for x86 and x64 architectures). At runtime, adal4j picks the
appropriate binary for the current platform and downloads and caches the
jar (uses HTTP ETags to automatically update the local cached version of
the jar in case a new version is found on the server). While the current
host for these jars is Github we can move this to an alternate location if
necessary.
<a href='#crh-start'></a><a href='#crh-data-%7B%22processed%22%3A%20%5B%22https%3A//github.com/AzureAD/azure-activedirectory-library-for-java/pull/20%23issuecomment-96523115%22%2C%20%22https%3A//github.com/AzureAD/azure-activedirectory-library-for-java/pull/20%23issuecomment-96797753%22%2C%20%22https%3A//github.com/AzureAD/azure-activedirectory-library-for-java/pull/20%23issuecomment-96837697%22%5D%2C%20%22comments%22%3A%20%7B%22General%20Comment%22%3A%20%7B%22html_url%22%3A%20%22https%3A//github.com/AzureAD/azure-activedirectory-library-for-java/pull/20%23issuecomment-96523115%22%2C%20%22comments%22%3A%20%5B%7B%22body%22%3A%20%22Hi%20__%40avranju__%2C%20I%27m%20your%20friendly%20neighborhood%20Microsoft%20Open%20Technologies%2C%20Inc.%20Pull%20Request%20Bot%20%28You%20can%20call%20me%20MSOTBOT%29.%20Thanks%20for%20your%20contribution%21%5Cr%5Cn%20%20%20%20%3Cp%3E%5Cr%5Cn%20%20%20%20%20%20%20%20It%20looks%20like%20you%27re%20a%20Microsoft%20contributor%20%28Rajasekharan%20Vengalil%20%28MS%20OPEN%20TECH%29%29.%20If%20you%27re%20full-time%2C%20we%20DON%27T%20require%20a%20Contribution%20License%20Agreement.%20If%20you%20are%20a%20vendor%2C%20please%20DO%20sign%20the%20electronic%20Contribution%20License%20Agreement.%20It%20will%20take%202%20minutes%20and%20there%27s%20no%20faxing%21%20https%3A//cla2.msopentech.com.%5Cr%5Cn%20%20%20%20%3C/p%3E%5Cr%5Cn%5Cr%5CnTTYL%2C%20MSOTBOT%3B%5Cr%5Cn%22%2C%20%22created_at%22%3A%20%222015-04-27T06%3A52%3A37Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/9519461%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/msotclas%22%7D%7D%2C%20%7B%22body%22%3A%20%22Thanks%20for%20this%20big%20chunk%20of%20code%21%20%40kpanwar%20will%20be%20doing%20the%20code%20review.%20We%20want%20to%20ensure%20that%20we%20can%20run%20server%20non-interactive%20without%20needing%20the%20interactive%20bits.%22%2C%20%22created_at%22%3A%20%222015-04-27T20%3A01%3A11Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/1471883%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/brandwe%22%7D%7D%2C%20%7B%22body%22%3A%20%22Sorry%20about%20the%20large%20PR.%20Github%27s%20diff%20view%20doesn%27t%20seem%20to%20handle%20%2Amovement%2A%20of%20files%20very%20well%20and%20instead%20shows%20the%20entire%20file%20as%20having%20changed.%20Pretty%20much%20the%20only%20change%20to%20existing%20code%20is%20in%20the%20addition%20of%20a%20new%20%60acquireToken%60%20overload%20to%20the%20%60AuthenticationContext%60%20class.%20Everything%20else%20is%20new%20code%20added%20to%20the%20%60com.microsoft.aad.adal4j.interactive.%2A%60%20package%20and%20the%20%2A%2Aadal-ad-interactive-auth%2A%2A%20module.%5Cr%5Cn%5Cr%5CnThe%20server%20side%20scenarios%20should%20continue%20to%20work%20as%20before.%22%2C%20%22created_at%22%3A%20%222015-04-27T22%3A21%3A06Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/628128%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/avranju%22%7D%7D%5D%2C%20%22title%22%3A%20%22General%20Comment%22%7D%7D%7D'></a>
<a href='https://www.codereviewhub.com/'></a>
- [ ] <a href='#crh-comment-General Comment'></a> &nbsp;<b><a href='https://github.com/AzureAD/azure-activedirectory-library-for-java/pull/20#issuecomment-96523115'>General Comment</a></b>
- <a href='https://github.com/msotclas'></a> Hi __@avranju__, I'm your friendly neighborhood Microsoft Open Technologies, Inc. Pull Request Bot (You can call me MSOTBOT). Thanks for your contribution!
<p>
It looks like you're a Microsoft contributor (Rajasekharan Vengalil (MS OPEN TECH)). If you're full-time, we DON'T require a Contribution License Agreement. If you are a vendor, please DO sign the electronic Contribution License Agreement. It will take 2 minutes and there's no faxing! https://cla2.msopentech.com.
</p>
TTYL, MSOTBOT;
- <a href='https://github.com/brandwe'></a> Thanks for this big chunk of code! @kpanwar will be doing the code review. We want to ensure that we can run server non-interactive without needing the interactive bits.
- <a href='https://github.com/avranju'></a> Sorry about the large PR. Github's diff view doesn't seem to handle *movement* of files very well and instead shows the entire file as having changed. Pretty much the only change to existing code is in the addition of a new `acquireToken` overload to the `AuthenticationContext` class. Everything else is new code added to the `com.microsoft.aad.adal4j.interactive.*` package and the **adal-ad-interactive-auth** module.
The server side scenarios should continue to work as before.

<a href='https://www.codereviewhub.com/AzureAD/azure-activedirectory-library-for-java/pull/20?mark_as_completed=1'></a>&nbsp;<a href='https://www.codereviewhub.com/AzureAD/azure-activedirectory-library-for-java/pull/20?approve=1'></a>&nbsp;<a href='https://github.com/AzureAD/azure-activedirectory-library-for-java/pull/20'></a>
<a href='#crh-end'></a>

### CODE REVIEW

**Comment by brandwe** [comment]
This pull request is now managed with CodeReviewHub. <a href='https://github.com/AzureAD/azure-activedirectory-library-for-java/pull/20'>Refresh</a>.<a href='#crh-update-none'></a>

**Comment by msotclas** [comment]
Hi __@avranju__, I'm your friendly neighborhood Microsoft Open Technologies, Inc. Pull Request Bot (You can call me MSOTBOT). Thanks for your contribution!
    <p>
        It looks like you're a Microsoft contributor (Rajasekharan Vengalil (MS OPEN TECH)). If you're full-time, we DON'T require a Contribution License Agreement. If you are a vendor, please DO sign the electronic Contribution License Agreement. It will take 2 minutes and there's no faxing! https://cla2.msopentech.com.
    </p>

TTYL, MSOTBOT;

**Comment by brandwe** [comment]
Thanks for this big chunk of code! @kpanwar will be doing the code review. We want to ensure that we can run server non-interactive without needing the interactive bits.

**Comment by avranju** [comment]
Sorry about the large PR. Github's diff view doesn't seem to handle *movement* of files very well and instead shows the entire file as having changed. Pretty much the only change to existing code is in the addition of a new `acquireToken` overload to the `AuthenticationContext` class. Everything else is new code added to the `com.microsoft.aad.adal4j.interactive.*` package and the **adal-ad-interactive-auth** module.

The server side scenarios should continue to work as before.

**Pull request closed without merging**
